### ISSUE TITLE
Request to support csv with header when using copy_from

### ISSUE THREAD

**Issue by neptune19821220** [PyGreSQL/PyGreSQL#39]
For PyGreSQL is supported in AWS Glue Python Shell Job, I use PyGreSQL to import the CSV result of Athena Query into RDS Postgresql.
The CSV result of Athena query has a first line as header, I found the parameter to deal with this issue in Postgres copy command, but it seems no such parameters in copy_from method.

Could you consider to add this improvement feature?
Thank you.

**Comment by Cito** [comment]
I think that has been left out on purpose because the PyGreSQL function takes streams as input, not filenames. If you have a stream, it is very easy to skip the first line (which is all that `header=true` would do), by calling `next(stream)` before calling `copy_from(stream)`, so you don't need that extra parameter.

**Comment by neptune19821220** [comment]
I think you are right.
Thanks.
