### ISSUE TITLE
DLL load failed: The operating system cannot run %1.

### ISSUE THREAD

**Issue by wintermonster** [PyGreSQL/PyGreSQL#50]
I just created a new environment using virtualenv and installed using _pip install PyGreSQL_

![image](https://user-images.githubusercontent.com/8009710/99200530-91b39880-27f1-11eb-9d6b-6234ee24823a.png)

**Comment by Cito** [comment]
Is libpq installed and the libpq.dll in your PATH? see first section here https://pygresql.org/contents/install.html

**Comment by nik-ahuja** [comment]
Hey @Cito  Thanks for the help, I have Postgres 10 and PgAdmin4 installed on my system - so I have added tried adding the following paths to the environment variable but nothing works : 
- C:\Program Files\PostgreSQL\10\bin
- C:\Program Files\PostgreSQL\10\pgAdmin 4\bin

Also, I have noticed that I only have 2 files pg.py and pgdb.py  in site-packages in my virtualenv and there's no _pg.pyd file as mentioned in the link that you shared.

**Comment by Cito** [comment]
@nik-ahuja The dll could also be called something like `_pg.cp38-win_amd64.pyd` but it should be installed. What output does "pip install PyGreSQL" give? Also make sure that you are using a 64 bit version of Python (since you seem to be using a 64 bit version of Postgres as well). Another problem may be that the wheel installed with "pip install" has been compiled against the libpq of PostgreSQL 12 in order to provide newer features only available there, so may not be able to work with the older libpq of PostgreSQL 10. You should install PostgreSQL 12 or at least the latest version of pgAdmin 4 (https://www.pgadmin.org/download/pgadmin-4-windows/). If you only do the latter, make sure the path with the new libpq comes first in the PATH environment variable. PyGreSQL in principle does also work with the older libpq, but then you must compile it yourself.

**Comment by nik-ahuja** [comment]
Hi @Cito thanks for your help, I downgraded my psqlodbc driver to v11 (earlier it was v12) - it resolved the issue. I am not exactly sure how and why though.

**Comment by Cito** [comment]
The psqlodbc driver comes with its own version of libpqdl.dll. If it's earlier in the PATH, then this version is used.

The current PyGreSQL should work with v12 of psqlodbc. Maybe you had a 32 bit version of psqlodb 12 and a 64 bit version Python or vice versa.
