### ISSUE TITLE
if  PyGresSQL  embeds the PostgreSQL query library why does it need libpq.dll ?

### ISSUE THREAD

**Issue by palminha** [PyGreSQL/PyGreSQL#75]
Since one of add value of PyGresSQL is that it "_**embeds the PostgreSQL query library**_", why does it needs `libpq.dll ` ?

```
ImportError: Cannot import shared library for PyGreSQL,
2probably because no libpq.dll is installed.
3DLL load failed while importing _pg: The specified module could not be found.
```

**Comment by Cito** [comment]
You're right, this wording can be misleading - "wraps" may be clearer. I have changed this now, even though the description was like that since 25 years or so... The goal of PyGreSQL was just to be a Python wrapper around the C API provided by libpq. PyGreSQL also predates the creation of the DB-API 2 standard, that's why you have the "classic" wrapper ("pg") and the DB-API 2 compliant wrapper ("pgdb"). Theoretically we could also compile PyGreSQL as a static library containing lipbq, and provide binaries including libpq, but it would mean additional efforts to maintain and test for the different platforms. Anybody who would want to work on this and maintain the binaries would of course be welcome (we have an open issue #54 for this already). And if you're looking for a pure Python PostgeSQL library, you can check out pg8000.

**Comment by palminha** [comment]
@Cito thanks for the impressive answer. Great community support! 

I'll have a look at the native python pg8000. Thanks!
